import 'package:firebase_core/firebase_core.dart';
import 'package:flutter/material.dart';
import 'package:provider/provider.dart';
import 'package:connect_app/login_screen.dart'; // Adjust if needed
import 'firebase_options.dart'; // Generated by flutterfire configure
import 'auth_provider.dart';

void main() async {
  WidgetsFlutterBinding.ensureInitialized();
  
  // Try to initialize Firebase, but don't fail if it doesn't work
  try {
    // Check if Firebase is already initialized
    try {
      Firebase.app();
    } catch (_) {
      // Firebase not initialized, try to initialize it
      await Firebase.initializeApp(options: DefaultFirebaseOptions.currentPlatform);
    }
  } catch (e) {
    // Silently continue without Firebase - the app will use mock mode
    // This is expected when Firebase is not configured or not available
  }
  
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MultiProvider(
      providers: [
        ChangeNotifierProvider(create: (_) => AuthProvider()),
      ],
      child: MaterialApp(
        debugShowCheckedModeBanner: false,
        title: 'Connect App',
        theme: ThemeData(primarySwatch: Colors.blue),
        home: const LoginScreen(),
      ),
    );
  }
}
